name:               "Data Dynamics"
description:        "A blog for Chris Morano - data scientist, pianist, curious explorer"

url:                ""
author:             "Chris Morano"
email:              "chrismorano@hotmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
email:              "chrismorano@hotmail.com"
github:             "chrismorano"
youtube:            "UCYzuXMj_hEV_fk_ZgnYCQkQ"
linkedin:           "dr-chris-morano"

disqus_shortname:   ""

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
