name:               "Data Dynamics"
description1:       "A blog by Dr. Chris Morano" 
description2:       "data scientist, classical pianist, curious explorer"

url:                ""
author:             "Chris Morano"
email:              "chrismorano@hotmail.com"
gravatar_hash:      "5e7a2153bf04ac9dfcd9f3292f13caac"
github:             "chrismorano"
youtube:            "UCYzuXMj_hEV_fk_ZgnYCQkQ"
linkedin:           "dr-chris-morano"

disqus_shortname:   ""

old_background:     "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"
background:         "https://raw.githubusercontent.com/chrismorano/chrismorano.github.io/master/assets/img/ethos-fuzziest.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Blog"
    href:           ""
  - name:           "Links"
    href:           "/links"
  - name:           "About Chris"
    href:           "/about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
